### PR TITLE
fix #840

### LINKED ISSUE #840: clean some unnecessary code
Please answer these questions before submitting your issue. Thanks!
开源不易，我们希望将精力放在完成新功能和解决有价值的问题上，为了让大家的配合更具有效率，请填写以下列出的全部问题

### Which version of Sharding-Sphere do you using?（您使用的Sharding-Sphere版本为？）
2.0.3 , branch : master
### 1、Useless object created
ShardingRule#createTableRuleWithDefaultDataSource， line 126
a new instance config is created but no where else in this method use the result
image1

### 2、instanceof will always return true 
WhereClauseParser#getColumnWithOwner ， line 232
propertyExpression.getOwner() will return an instance of SQLIdentifierExpression,so it's no need to do the instanceof check
image2

### 3、double assignment
 DefaultKeyGenerator#generateKey， line 104
the assignment  of sequence++   is useless because of the final value of sequence is (sequence + 1) & SEQUENCE_MASK , sequence + 1 could be better
image3

### Please provide the reproduce example codes (such as github link)，otherwise we will label the issue as Invalid and close it.（为了节省复现问题的时间，请务必提供可重现的代码，否则我们会将issue直接标记为invalid并关闭）

Code should based on https://github.com/sharding-sphere/sharding-sphere-example
（代码请基于 https://github.com/sharding-sphere/sharding-sphere-example）

### PR DESCRIPTION
**Pull request by hqq2023623**
Fixes #ISSUSE_ID.

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by tuohai666** [comment]
Hi hqq2023623, could you please resolve these conflicts? I notice that the problem in ShardingRule has already bean solved.

**Comment by hqq2023623** [comment]
some modules have been renamed , it's easier by creating a new pr than resolving the conflicts

**Comment by tuohai666** [comment]
Thanks to your effort. We planed to merge your pr after M1 launching.

**Comment by terrymanu** [comment]
I think we can merge now, the code is fine

**Pull request merged**
